name: Build e Publicação no Docker Hub

on:
  push:
    branches:
      - main  # Dispara apenas quando houver push na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile  # Caminho para o Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jogo-legal-novo:latest
